---
name: 'Issue Title AI'
description: 'Improves GitHub issue titles to make them more catchy and helpful using LLM'
author: 'Igor Udot <horw7001@gmail.com>'
branding:
  icon: 'edit-3'
  color: 'blue'
inputs:
  github-token:
    description: >
      GitHub token to access the repository issues
    required: true
  gemini-api-key:
    description: >
      Google Gemini API key for LLM integration
    required: false
  gemini-model:
    description: >
      Google Gemini LLM model to use
    required: false
  openai-api-key:
    description: >
      OpenAI API key for LLM integration
    required: false
  openai-model:
    description: >
      OpenAI LLM model to use
    required: false
  deepseek-api-key:
    description: >
      DeepSeek API key for LLM integration
    required: false
  deepseek-model:
    description: >
      DeepSeek LLM model to use
    required: false
  ai-provider:
    description: >
      By default, the LLM provider is chosen based on the provided API key.
      However, if there are multiple keys, a random provider will be selected.
      In this case, you should explicitly specify one of the following: gemini, openai, or deepseek.
    required: false
  verbose:
    description: >
      When enabled, prints detailed information including:
      - The input provided to the model
      - The model's response
      - Token usage statistics
      Useful for debugging or understanding model behavior.
    default: 'false'
  max-issues:
    description: >
      Maximum number of issues that will be retrieved from GitHub.
      This setting does not apply when triggered by an open issue..
    default: '100'
  required-labels:
    description: >
      Filter issues by specific labels (comma-separated). Only issues with at least one of the specified labels will be processed.
      Example: "bug, enhancement" will process only issues labeled as bug or enhancement.
    required: false
  strip-characters:
    description: >
      The best practice is to specify the prompt correctly. However, sometimes the model may return responses
      enclosed in unwanted characters, such as quotes (""). This option allows you to define which characters
      should be stripped from the beginning and end of the response. The specified characters will be removed
      using Python's `strip()` function.
      Example: Using `'"` will remove the characters `"`, `'` from both ends of the response.
  days-to-scan:
    description: >
      Number of days to look back for issues
    required: false
    default: '7'
  auto-update:
    description: >
      Automatically update issue titles without confirmation
    required: false
    default: 'false'
  apply-to-closed:
    description: >
      Process both open and closed issues. By default, only open issues are processed.
    required: false
    default: 'false'
  quiet:
    description: >
      By default, auto-update adds a comment to your pull request.
      You can skip this behavior by setting this parameter to 'true',
      which will prevent the comment from being added.
    default: 'false'
  skip-label:
    description: >
      Label to mark processed issues
    required: false
  style:
    description: >
      Predefined prompt.
      To view available prompts, refer to the `styles` folder `https://github.com/horw/issue-title-ai/tree/main/styles`.
      If you’d like to add a new style and share it with others, please add your file to the folder and submit a pull request (PR).
    default: "summary"
    required: false
  prompt:
    description: >
      A custom prompt for the AI model.
      This will override the selected style, if provided.
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
